#!/bin/sh

#
#  STEP 2:
#  convert all evasys message strings into a binary format
#

LOCALE_RELATIVE_PATH="."

for language in en
do
	test -f "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/evasys.mo" && mv "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/evasys.mo" "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/evasys.mo.old"
	msgfmt "$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/evasys.po" --output-file="$LOCALE_RELATIVE_PATH/$language/LC_MESSAGES/evasys.mo"
done
